### ISSUE TITLE
Aokana Font - Fan Translation

### ISSUE THREAD

**Issue by foubou** [Adebasquer/AokanaPatch#1]
Hello Adebasquer !
First of all, let me thank you for your amazing tools. I've been able to extarct/modify/insert texts properly.
My teamate and I are trying to translate the game in French, but we have a major issue with the font.
The french diatric letters are not supported !
Unfortunately, none of us has the skills to edit the font files.
We absolutely need the following characters : éèêëÉÊàâÀçÇïôîùûœ
Do you think you can help us ?

**Comment by Adebasquer** [comment]
I just added a way to load fonts with the patcher. It's kind of involved because Aokana's older version of Unity doesn't really have the tools I need to load fonts directly from ttf files so that Textmesh Pro (the plugin Aokana uses to display text) can use them, but it seems to work this way.
Here's a tutorial I made: https://github.com/Adebasquer/AokanaPatch/wiki/Font-Tutorial. 
Let me know if you run into bugs in another issue if needed.

**Comment by foubou** [comment]
Thank you very much for adding font support and for the tutorial.
If we encounter any bugs, we'll make sure to let you know ! 👍

**Comment by foubou** [comment]
We were unable to make BepInEx and AokanaPatch.dll work.

Is there a specific version of BepInEx and a specific version of the game we should use ?

We tried on game v1.0 and game patched v1.21 [Perfect Edition+R18], but nothing worked.
I read we should be able to config BepInEx, but no config file was created, even after launching the game.
Here is the font file we generated after following your tutorial : [font.zip](https://github.com/Adebasquer/AokanaPatch/files/6561164/font.zip)

This is the last step for us, the last problem we need to solve to start our translation in the best conditions.

Thank you for taking the time to help us !
